[package]
name = "circadian"
version = "0.1.0"
authors = ["Trevor Bentley <trevor@trevorbentley.com>"]
description = "Linux auto-suspend/wake power management daemon"
keywords = ["linux", "power", "suspend", "daemon", "service"]
categories = []
homepage = "https://github.com/mrmekon/circadian"
repository = "https://github.com/mrmekon/circadian"
documentation = "https://github.com/mrmekon/circadian"
license = "GPL-3.0"

[profile.release]
lto = true

[dependencies]
regex = "0.2"
glob = "0.2.11"
rust-ini = "0.10.0"
clap = "2.27.1"
time = "0.1.38"
nix = "0.9.0"
